export default {
appLogo: require('./images/logo.png'),
bag: require('./images/bag.png'),
Logo1: require('./images/Logo1.png'),
Success: require('./images/Success.png'),


otp2: require('./images/otp2.png'),
face1: require('./images/face1.png'),
phonLogoapp: require('./images/phonLogoapp.png'),
Editpen: require('./images/Editpen.png'),
sp1: require('./images/sp1.png'),
ProfilAtvie: require('./images/ProfilAtvie.png'),
lock: require('./images/lock.png'),
identityimage: require('./images/identityimage.png'),
hide: require('./images/hide.png'),
smsImg: require('./images/smsImg.png'),
docSlied: require('./images/docSlied.png'),
Check1: require('./images/Check1.png'),
search1: require('./images/search.png'),
profive: require('./images/profive.png'),
Phone1: require('./images/Phone1.png'),
Iconreceiv: require('./images/Iconreceiv.png'),
helpPrva: require('./images/helpPrva.png'),
wallet: require('./images/wallet.png'),
wallets: require('./images/wallets.png'),
tader: require('./images/tader.png'),
profiel: require('./images/profiel.png'),
trder1: require('./images/trder1.png'),
home1: require('./images/home1.png'),
homwActive: require('./images/homwActive.png'),
Btc: require('./images/Btc.png'),
sp2: require('./images/sp2.png'),
Sell: require('./images/Sell.png'),
Swap: require('./images/Swap.png'),

 

Polygon: require('./images/Polygon.png'),
Received: require('./images/Received.png'),
Next: require('./images/Next.png'),
Buy: require('./images/Buy.png'),
icons: require('./images/icons.png'),
Vector: require('./images/Vector.png'),
Notification: require('./images/Notification.png'),
document: require('./images/document.png'),
Ellipse: require('./images/Ellipse.png'),
trck: require('./images/trck.png'),
Dots: require('./images/Dots.png'),
arrowqdown: require('./images/arrowqdown.png'),
cars: require('./images/cars.png'),
more_vert: require('./images/more_vert.png'),
Rectangle: require('./images/Rectangle.png'),

black: require('./images/black.png'),
location1: require('./images/location1.png'),
group: require('./images/group.png'),
right: require('./images/arrowRight.png'),
Icon: require('./images/Icon.png'),
apple: require('./images/apple.png'),
google: require('./images/google.png'),
Mesonmorpah: require('./images/Mesonmorpah.png'),
MohronFag: require('./images/MohronFag.png'),
prfile: require('./images/prfile.png'),
pushup: require('./images/pushup.png'),
running: require('./images/running.png'),
back: require('./images/back.png'),
cycling: require('./images/cycling.png'),
arrowDown: require('./images/arrowDown.png'),
logout: require('./images/logout.png'),
Filter: require('./images/Filter.png'),
dounArroww: require('./images/dounArroww.png'),
aboutus: require('./images/aboutus.png'),
BackLeft: require('./images/BackLeft.png'),
Ellipsa: require('./images/Ellipsa.png'),
userLogo: require('./images/userLogo.png'),
deliver: require('./images/Deliver.png'),
Email: require('./images/Email.png'),
Matici: require('./images/matici.png'),
Ethereum: require('./images/Ethereum.png'),
Bnb: require('./images/Bnb.png'),
More: require('./images/more.png'),
Scanning: require('./images/scanning.png'),
Nofiication: require('./images/nofiication.png'),
Waliert: require('./images/waliert.png'),

cosrimge: require('./images/cosrimge.png'),
conved: require('./images/conved.png'),
vivies: require('./images/vivies.png'),
withod: require('./images/withod.png'),
walletw: require('./images/walletw.png'),






}; 